<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-6PU7QPRN" failures="0" tests="3" name="Testcase.HomeTest" time="6.131" errors="1" timestamp="02 Jul 2022 08:08:17 GMT" skipped="0">
  <testcase classname="Testcase.HomeTest" name="validateUsernameTitleTest" time="0.016">
    <error message="class jdk.proxy2.$Proxy11 cannot be cast to class java.lang.CharSequence (jdk.proxy2.$Proxy11 is in module jdk.proxy2 of loader &#039;app&#039;; java.lang.CharSequence is in module java.base of loader &#039;bootstrap&#039;)" type="java.lang.ClassCastException">
      <![CDATA[java.lang.ClassCastException: class jdk.proxy2.$Proxy11 cannot be cast to class java.lang.CharSequence (jdk.proxy2.$Proxy11 is in module jdk.proxy2 of loader 'app'; java.lang.CharSequence is in module java.base of loader 'bootstrap')
at Page.HomePage.validateUserName(HomePage.java:38)
at Testcase.HomeTest.validateUsernameTitleTest(HomeTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- validateUsernameTitleTest -->
  <testcase classname="Testcase.HomeTest" name="creatingPost" time="5.417"/>
  <testcase classname="Testcase.HomeTest" name="clickingOnPost" time="0.698"/>
</testsuite> <!-- Testcase.HomeTest -->
